# Generated by Django 3.0.7 on 2020-06-29 20:13

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200629_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.get_file_path, verbose_name='Imagem'),
        ),
    ]
