# Generated by Django 3.0.7 on 2020-06-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200615_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(upload_to='media/%Y/%m/%d/'),
        ),
    ]
