# Generated by Django 3.0.7 on 2020-06-16 20:20

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200616_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(upload_to=posts.models.get_file_path),
        ),
    ]
