# Generated by Django 3.0.7 on 2020-06-25 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20200624_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='autor',
            new_name='user',
        ),
    ]
