# Generated by Django 3.0.7 on 2020-07-11 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_auto_20200711_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsanswer',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Comments', verbose_name='Comentário'),
        ),
    ]
