# Generated by Django 3.0.8 on 2020-07-17 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_auto_20200711_1853'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentsAnswer',
        ),
    ]
