# Generated by Django 3.0.8 on 2020-07-17 20:53

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_auto_20200717_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, default='profiles/avatar.png', null=True, upload_to=posts.models.get_file_path, verbose_name='Imagem'),
        ),
    ]
