# Generated by Django 3.0.8 on 2020-07-17 21:03

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_auto_20200717_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, default='/media/static/avatar.png', null=True, upload_to=posts.models.get_file_path, verbose_name='Imagem'),
        ),
    ]
