# Generated by Django 3.0.8 on 2020-07-17 21:05

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_auto_20200717_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(default='/media/profiles/avatar.png', upload_to=posts.models.get_file_path, verbose_name='Imagem'),
        ),
    ]
