# Generated by Django 3.0.8 on 2020-07-17 21:40

from django.db import migrations
import django_fields.fields
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0031_auto_20200717_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=django_fields.fields.DefaultStaticImageField(blank=True, upload_to=posts.models.get_file_path),
        ),
    ]
