# Generated by Django 3.0.8 on 2020-07-20 19:09

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0034_auto_20200720_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=posts.models.get_file_path, verbose_name='Imagem'),
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
