# Generated by Django 3.0.7 on 2020-07-25 20:08

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('posts', '0038_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='Comments',
            field=models.TextField(null=True, verbose_name='Respostas'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='Suas tags', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
