# Generated by Django 3.0.7 on 2020-07-25 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0039_auto_20200725_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='Comments',
        ),
        migrations.AddField(
            model_name='comments',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Respostas', to='posts.Comments'),
        ),
    ]
